function foo() {
  throw new Error('oof')
  return '123'
}

function bar() {
  try {
    return foo()
  } catch (e) {
    console.error(e)
    throw e
  }
}

export default {
  async fetch(request) {
    const id = bar()
    const html = `<!DOCTYPE html>
		<body>
		  <h1>Hello World ${id}</h1>
		  <p>This markup was generated by a Cloudflare Worker.</p>
		</body>`

    return new Response(html, {
      headers: {
        'content-type': 'text/html;charset=UTF-8',
      },
    })
  },
}
